### ISSUE TITLE
Cannot build Clang 11.1.0 on Ubuntu 18.04

### ISSUE THREAD

**Issue by mbautin** [yugabyte/build-clang#1]
[1188/2409] Building X86GenEVEX2VEXTables.inc...
[1189/2409] Linking CXX shared library lib/libLLVMObject.so.11
FAILED: lib/libLLVMObject.so.11
: && /usr/bin/g++ -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/opt/yb-build/llvm/yb-llvm-v11.1.0-1630705904-1fdec59b-ubuntu20.04-x86_64-build/stage-1/build/./lib  -Wl,-O3 -Wl,--gc-sections -shared -Wl,-soname,libLLVMObject.so.11 -o lib/libLLVMObject.so.11 lib/Object/CMakeFiles/LLVMObject.dir/Archive.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Binary.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFImportFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFModuleDefinition.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Decompressor.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ELF.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ELFObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Error.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/IRObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/IRSymtab.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/MachOObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/MachOUniversal.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Minidump.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ModuleSymbolTable.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Object.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/RecordStreamer.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/RelocationResolver.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/SymbolicFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/SymbolSize.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/TapiFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/TapiUniversal.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/WasmObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/WindowsMachineFlag.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/WindowsResource.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/XCOFFObjectFile.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMBitReader.so.11  lib/libLLVMCore.so.11  lib/libLLVMMCParser.so.11  lib/libLLVMTextAPI.so.11  lib/libLLVMMC.so.11  lib/libLLVMBinaryFormat.so.11  lib/libLLVMSupport.so.11  -Wl,-rpath-link,/opt/yb-build/llvm/yb-llvm-v11.1.0-1630705904-1fdec59b-ubuntu20.04-x86_64-build/stage-1/build/lib && :
/usr/bin/ld: lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o: in function `llvm::writeArchive(llvm::StringRef, llvm::ArrayRef<llvm::NewArchiveMember>, bool, llvm::object::Archive::Kind, bool, bool, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >)':
ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x173c): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x176f): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x179a): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x17c5): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x17f0): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/bin/ld: lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o:ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x182f): more undefined references to `llvm::raw_string_ostream::current_pos() const' follow
collect2: error: ld returned 1 exit status
[1190/2409] Building AArch64GenAsmWriter1.inc...
[1191/2409] Building AArch64GenCallingConv.inc...
[1192/2409] Building X86GenRegisterBank.inc...
[1193/2409] Building X86GenRegisterInfo.inc...
[1194/2409] Building CXX object lib/LTO/CMakeFiles/LLVMLTO.dir/LTOCodeGenerator.cpp.o
[1195/2409] Building AArch64GenAsmMatcher.inc...
[1196/2409] Building CXX object lib/Target/CMakeFiles/LLVMTarget.dir/TargetMachineC.cpp.o
[1197/2409] Building AArch64GenPostLegalizeGICombiner.inc...
[1198/2409] Building AArch64GenMCPseudoLowering.inc...
[1199/2409] Building X86GenDisassemblerTables.inc...
[1200/2409] Building AArch64GenMCCodeEmitter.inc...
[1201/2409] Building CXX object lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFDie.cpp.o
[1202/2409] Building AArch64GenRegisterBank.inc...
[1203/2409] Building AArch64GenDisassemblerTables.inc...
[1204/2409] Building CXX object lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFDebugLine.cpp.o
[1205/2409] Building AArch64GenFastISel.inc...
[1206/2409] Building CXX object lib/Target/CMakeFiles/LLVMTarget.dir/TargetLoweringObjectFile.cpp.o
[1207/2409] Building CXX object lib/Target/CMakeFiles/LLVMTarget.dir/TargetMachine.cpp.o
[1208/2409] Building CXX object lib/LTO/CMakeFiles/LLVMLTO.dir/LTOBackend.cpp.o
[1209/2409] Building CXX object lib/Analysis/CMakeFiles/LLVMAnalysis.dir/ValueTracking.cpp.o
[1210/2409] Building X86GenSubtargetInfo.inc...
[1211/2409] Building CXX object lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFUnit.cpp.o
[1212/2409] Building CXX object lib/LTO/CMakeFiles/LLVMLTO.dir/LTO.cpp.o
[1213/2409] Building CXX object lib/LTO/CMakeFiles/LLVMLTO.dir/ThinLTOCodeGenerator.cpp.o
[1214/2409] Building CXX object lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFContext.cpp.o
[1215/2409] Building X86GenFastISel.inc...
[1216/2409] Building AArch64GenDAGISel.inc...
[1217/2409] Building X86GenGlobalISel.inc...
[1218/2409] Building CXX object lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFVerifier.cpp.o
[1219/2409] Building AArch64GenInstrInfo.inc...
[1220/2409] Building X86GenInstrInfo.inc...
[1221/2409] Building X86GenDAGISel.inc...
[1222/2409] Building CXX object lib/Analysis/CMakeFiles/LLVMAnalysis.dir/ScalarEvolution.cpp.o
ninja: build stopped: subcommand failed.
[helpers.py:61] 2021-09-03 22:13:11,197 INFO: Changing directory back to: /home/yugabyteci/build-clang
Traceback (most recent call last):
  File "/home/yugabyteci/build-clang/src/build_clang/build_clang_main.py", line 727, in <module>
    main()
  File "/home/yugabyteci/build-clang/src/build_clang/build_clang_main.py", line 723, in main
    builder.run()
  File "/home/yugabyteci/build-clang/src/build_clang/build_clang_main.py", line 664, in run
    stage.build()
  File "/home/yugabyteci/build-clang/src/build_clang/build_clang_main.py", line 456, in build
    run_cmd(['ninja', target])
  File "/home/yugabyteci/build-clang/src/build_clang/helpers.py", line 43, in run_cmd
    subprocess.check_call(args, cwd=effective_directory)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'clang']' returned non-zero exit status 1.
yugabyteci@df0da0f8fd9b:~/build-clang$ wd
-bash: wd: command not found
yugabyteci@df0da0f8fd9b:~/build-clang$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
yugabyteci@df0da0f8fd9b:~/build-clang$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

**Comment by mbautin** [comment]
No longer relevant. Both Clang 11 and Ubuntu 18.04 are too old.
