### ISSUE TITLE
Support build with LTO for Clang 17

### ISSUE THREAD

**Issue by mbautin** [yugabyte/build-clang#9]
We need to build Clang 17 with LTO. Currently getting the following error:

[444/3020] Building IntrinsicsR600.h...
FAILED: include/llvm/IR/IntrinsicsR600.h /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include/llvm/IR/IntrinsicsR600.h
cd /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build && /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen -gen-intrinsic-enums -intrinsic-prefix=r600 -I /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/IR -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsR600.h -d include/llvm/IR/IntrinsicsR600.h.d
/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
[445/3020] Building OMP.h.inc...
FAILED: include/llvm/Frontend/OpenMP/OMP.h.inc /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include/llvm/Frontend/OpenMP/OMP.h.inc
cd /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build && /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen --gen-directive-decl -I /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/Frontend/OpenMP -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/Frontend/OpenMP/OMP.td --write-if-changed -o include/llvm/Frontend/OpenMP/OMP.h.inc -d include/llvm/Frontend/OpenMP/OMP.h.inc.d
/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
[446/3020] Building OMP.inc...
FAILED: include/llvm/Frontend/OpenMP/OMP.inc /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include/llvm/Frontend/OpenMP/OMP.inc
cd /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build && /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen --gen-directive-impl -I /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/Frontend/OpenMP -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/Frontend/OpenMP/OMP.td --write-if-changed -o include/llvm/Frontend/OpenMP/OMP.inc -d include/llvm/Frontend/OpenMP/OMP.inc.d
/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
[447/3020] Building RISCVTargetParserDef.inc...
FAILED: include/llvm/TargetParser/RISCVTargetParserDef.inc /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include/llvm/TargetParser/RISCVTargetParserDef.inc
cd /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build && /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen -gen-riscv-target-def -I /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/lib/Target/RISCV/ -I /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include/llvm/TargetParser -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/include -I/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/include /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/src/llvm-project/llvm/lib/Target/RISCV/RISCV.td --write-if-changed -o include/llvm/TargetParser/RISCVTargetParserDef.inc -d include/llvm/TargetParser/RISCVTargetParserDef.inc.d
/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/stage-4/build/bin/llvm-min-tblgen: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
[448/3020] Linking CXX executable bin/clang-tblgen
ninja: build stopped: subcommand failed.
[helpers.py:65] 2023-09-15 22:25:57,496 INFO: Changing directory back to: /home/mbautin/code/build-clang

Traceback (most recent call last):
  File "/home/mbautin/code/build-clang/src/build_clang/build_clang_main.py", line 18, in <module>
    main()
  File "/home/mbautin/code/build-clang/src/build_clang/build_clang_main.py", line 14, in main
    builder.run()
  File "/home/mbautin/code/build-clang/src/build_clang/clang_builder.py", line 255, in run
    stage.build()
  File "/home/mbautin/code/build-clang/src/build_clang/clang_build_stage.py", line 369, in build
    self._run_ninja([target])
  File "/home/mbautin/code/build-clang/src/build_clang/clang_build_stage.py", line 294, in _run_ninja
    run_cmd(ninja_args)
  File "/home/mbautin/code/build-clang/src/build_clang/helpers.py", line 47, in run_cmd
    subprocess.check_call(args, cwd=effective_directory)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'cxxabi']' returned non-zero exit status 1.

**Comment by mbautin** [comment]
Apparently rpath is not set on the binary that is being built with LTO:


/opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build $ find . -name "*tblgen"
./src/llvm-project/mlir/include/mlir/Tools/mlir-tblgen
./src/llvm-project/mlir/lib/Tools/mlir-tblgen
./src/llvm-project/mlir/test/mlir-tblgen
./src/llvm-project/mlir/tools/mlir-tblgen
./src/llvm-project/utils/bazel/llvm-project-overlay/mlir/test/mlir-tblgen
./stage-1/build/bin/llvm-min-tblgen
./stage-1/build/bin/llvm-tblgen
./stage-1/build/bin/clang-tblgen
./stage-1/installed/bin/llvm-tblgen
./stage-1/installed/bin/clang-tblgen
./stage-2/build/bin/llvm-min-tblgen
./stage-2/build/bin/llvm-tblgen
./stage-2/build/bin/clang-tblgen
./stage-2/installed/bin/llvm-tblgen
./stage-2/installed/bin/clang-tblgen
./stage-3/build/bin/llvm-min-tblgen
./stage-3/build/bin/llvm-tblgen
./stage-3/build/bin/clang-tblgen
./stage-3/build/bin/lldb-tblgen
./stage-4/build/bin/llvm-min-tblgen
./stage-4/build/bin/clang-tblgen
2023-09-16T00:08:06 mbautin@dev-server-mbautin-us-east4-b /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build $ ldd ./stage-3/build/bin/llvm-min-tblgen
	linux-vdso.so.1 (0x00007ffdcc9d8000)
	libLLVMTableGen.so.17rc => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/libLLVMTableGen.so.17rc (0x00007f83dea2f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f83de687000)
	libLLVMSupport.so.17rc => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/libLLVMSupport.so.17rc (0x00007f83de477000)
	libc++.so.1 => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/x86_64-unknown-linux-gnu/libc++.so.1 (0x00007f83de929000)
	libc++abi.so.1 => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/x86_64-unknown-linux-gnu/libc++abi.so.1 (0x00007f83de8e7000)
	libunwind.so.1 => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/x86_64-unknown-linux-gnu/libunwind.so.1 (0x00007f83de8d7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f83de0f5000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f83ddedd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f83ddb18000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f83de8a7000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f83dd910000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f83dd70c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f83dd4f4000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f83dd2c7000)
	libLLVMDemangle.so.17rc => /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build/./stage-3/build/bin/../lib/../lib/libLLVMDemangle.so.17rc (0x00007f83dd279000)
	libatomic.so.1 => /lib64/libatomic.so.1 (0x00007f83dd071000)
2023-09-16T00:08:10 mbautin@dev-server-mbautin-us-east4-b /opt/yb-build/llvm/yb-llvm-v17.0.0-rc4-yb-1-1694814923-f4941784-almalinux8-x86_64-build $ ldd ./stage-4/build/bin/llvm-min-tblgen
	linux-vdso.so.1 (0x00007fff57fbd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f14cb32f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f14cb127000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f14caf23000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f14caba1000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f14ca989000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f14ca75c000)
	libc++.so.1 => not found
	libc++abi.so.1 => not found
	libunwind.so.1 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f14ca397000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f14cb54f000)

**Comment by mbautin** [comment]
readelf result:

$ readelf -d ./stage-4/build/bin/llvm-min-tblgen

Dynamic section at offset 0xf8210 contains 37 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib/x86_64-unknown-linux-gnu:$ORIGIN/../../../stage-3/installed/lib/x86_64-unknown-linux-gnu:$ORIGIN/../lib]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libtinfo.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc++.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc++abi.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libunwind.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000006ffffffb (FLAGS_1)            Flags: PIE
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000007 (RELA)               0x2060
 0x0000000000000008 (RELASZ)             75456 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          2822
 0x0000000000000017 (JMPREL)             0x14720
 0x0000000000000002 (PLTRELSZ)           3000 (bytes)
 0x0000000000000003 (PLTGOT)             0xfb768
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x320
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x12b8
 0x000000000000000a (STRSZ)              3496 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1290
 0x0000000000000019 (INIT_ARRAY)         0xf2fe0
 0x000000000000001b (INIT_ARRAYSZ)       72 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xf3028
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000000000000c (INIT)               0xf17c8
 0x000000000000000d (FINI)               0xf17e4
 0x000000006ffffff0 (VERSYM)             0x10a0
 0x000000006ffffffe (VERNEED)            0x11c0
 0x000000006fffffff (VERNEEDNUM)         5
 0x0000000000000000 (NULL)               0x0
